### ISSUE TITLE
couple of small things :)

### ISSUE THREAD

**Issue by czb** [inad9300/Soil#3]
Wow, perfect library! Just what I was looking for ;).

Many years ago I started with JQuery, then continued with Knockout, VueJS, React, Mithril. Just recently I realised that virtual DOM is overkill for most situations so I started playing with RE:DOM. I did not like the experience (I love TypeScript). And now I found Soil! 👍 Together with Type-Style it will cover most of my needs ;). Thanks for the hard work you put into it!

I have a couple of tiny little comments:

* `h.form([])` does not shoot a type error but it should probably because it fails in runtime
* Some types in `lib.es2016.full.d.ts` such as `HTMLSelectElement` contain `[name: string]: any;` which then allows to add e.g. `class` as attribute, which does not work. I do not know the reasoning of the TypeScript team behind but I would probably prefer to shoot an error if an unknown property was added to e.g. `h.select` element. What do you think about it?

**Comment by czb** [comment]
I like the idea of having a simple and type safe alternative to RE:DOM. I understand it is not production ready but since it is a small library it is quite easy to tailor make it for a particular use case. The only thing that limits somehow the use is the licence. Maybe you could consider MIT which is the licence all the aforementioned libraries use. What do you think?

**Comment by inad9300** [comment]
It would be awesome to have such a parser! Writing scripts to extract the information from different W3C specs is something I'm working on these days, since so far I've been putting everything together manually. It is definitely the way to go.

Having a closer look at TypeStyle and reusing part of their work crossed my mind too. The optimal solution would be to have the TypeScript team incorporate this into their type definitions ;) I have made such a proposal in https://github.com/Microsoft/TypeScript/issues/17827, and they seem to be discussing it. I would like to focus on other things for the moment and give some time for this to evolve. But to me is almost a requirement – this project wouldn't be complete without type-safe CSS, considering it is part of the interfaces we have to interact with HTML elements.

Regarding licensing, it is a complex topic of which I only know a couple of things. To the best of my knowledge, GPLv3 and AGPLv3 are the only licenses that guarantee no harm is done to the ultimate users of software, by respecting their fundamental freedoms, which is my main concern and the reason I chose AGPLv3. In particular, the MIT license does not require the source code of derivate work to be disclosed. I would like nevertheless to understand how is AGPv3 limiting for you, and perhaps we can work something out.

**Comment by czb** [comment]
I give you an example. I have developed a piano game:

https://github.com/czb/musicope

and I would like people to use it as they like (no restrictions at all). I have just included part of your source code here (as I do not need the remaining code):

https://github.com/czb/musicope/blob/master/static/web/soil.ts

I am almost certain that I have just violated the AGPL license. I have modified you source code and incorporated it into my app. Thus my app has to be under AGPL not to violate the license. But I do not want to limit the use of my app by any means - MIT is fine for me.

Do you see the problem? With AGPL I will be forced to remove the Soil code and find an alternative...

**Comment by czb** [comment]
Probably the quickest solution might be to write a script converting:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts

What do you think?

**Comment by inad9300** [comment]
I understand (a subset of) the constraints GPL sets on derivative work. Some might seem restrictive to the developer, but they are in the best interest of end users. If you choose MIT, we are only one step away from causing harming them – now someone could use or modify your work and distribute it to users without disclosing its source, depriving them from one of their fundamental freedoms. If it is on my hand, I would prefer this not to happen with derivate work of mine.

By the way, why are you not depending on the published npm package? Copying files around reminds me of earlier stages of software development. Perhaps there is something I could improve on that would help you with this...?

Regarding your idea of using React's type definitions, I have not thought of that before and is a good idea in principle. In practice though, it's not clear to me what is their criteria creating these files. After having look, I can already see some problematic parts, such as the inclusion of React-specific and non-standard attributes, or the arbitrary modification of some standard properties such as `onclick`, which they replace with `onClick`. This later case is also weird in that they seem to redefine the meaning of "attribute" completely: `onClick` lives in the `DOMAttributes` interface, but it maps to an event handler rather than to a `string`, which is something you would expect for *properties* but not for *attributes*. In this sense, React seems to be separated enough from the standards to discard using their type definitions.

Additionally, parsing TypeScript seems to me a more complicated task than parsing HTML. For this reason as well, I was thinking on relying directly on [the HTML5 specification](https://www.w3.org/TR/html51/single-page.html) to build the type definitions. Of course it comes with its own complications... At the end is quite difficult to tell what is the simplest path, but I feel more like starting by the spec.

**Comment by inad9300** [comment]
Using your work, modifying it and not disclosing its source is totally fine by GPL standards. The problematic part is to distribute it then. In other words, *it is not right* to provide people with a tool they do not know how it works, they cannot ensure the safety of, they cannot learn from and they cannot modify to their convenience. This is not a good contribution to society – rather, it helps spread the wrong value system. No person should be in the situation to have to choose a tool like this.

I would be glad to hear your opinions on npm :) I have not encountered anyone before who preferred copying files over using npm, I'm really curious about your reasons.

I did not know about CSSType, nor about [MDN data](https://github.com/mdn/data), they look really promising! Thanks for sharing.

**Comment by czb** [comment]
Maybe you are right in the reasoning but for me it is quite simple. I want people to use my app - therefore I put as little obstacles in using it as possible. ;) BTW: There must be a reason why all famous libraries use MIT and not GPL ;) But enough about licensing - it is almost as bad as spaces vs. tabs ;). Just let me know if I can keep the file when using MIT or if I shall remove it.

Regarding NPM. It is not that much a problem of concept of libraries rather a problem of how NPM and NodeJS works. Web is based on simple security concept which says everything is forbidden and then a comity decides what to allow. On the other hand there is C#, C++, Python and also unfortunately NodeJS that simply allow everything and then do magic such as `runInContext` to limit it if necessary. With NPM thousands of packages are normally installed and all the packages have access to everything. My opinion is that 99% of the NPM packages could be just fine with features client web provides.

So if I were to develop NodeJS today I would run all the scripts in "Chromium" like environment. For anything extra, I would use Websockets to communicate with the server part. Similarly to how puppeteer communicates with NodeJS. I am sure it would solve most of the problems we have today. All the code would simply be client code, period. Today there is a part of Typescript for NodeJS which does not work in browser, there is VSCode that does not work in browser, there is Prettier that does not work in browser and I could continue forever. And why? Because of bad decisions on how NodeJS should be built.

A little background. I build an online development and runtime tool that is based on that concept that I just described. The main idea is "democratising" development. I.e. it must be extremely simple for newcomers => forget bundling, ts compilation, git, publishing, alarms etc... Everything must just work and everything is based on client side to have a robust sandbox so people do not have to be afraid of using it and by a mistake destroying the universe. It works perfectly but requires not using NPM because it is inherently unsafe and NodeJS based... So I use NodeJS to provide the gatekeeper to the server side and everything else is client side (even the user server side is for me a client side :))

As mentioned it is nothing that can be described in a short description. I use to discuss it in hours and hours when talking about that topic :) But hopefully it gives you an idea.

PS: your case is even more special because it is "just" a couple of helping functions so it is easy to include in the heart of the code instead of linking it as a library. Normally I link libraries => they are just strictly client side.

**Comment by inad9300** [comment]
I understand your point of view, but I believe it is not enough. Also, I don't think freedom compares with stylistic matters such as the use of space or tabs, I have to say. And I'm sure there are reasons why different people and companies use the MIT license. One such known reason is that they want to increase their popularity, and they put this before more important values. Another simple explanation is that they haven't given enough thought to the implications of their licensing decisions. Or that, *hey, that's what others do!*

I see a shred of contradiction in your words. You want to help users and developers by offering your work and using a permissive license (assuming helping is your goal, as opposed to something like getting credit), but at the same time you are not concerned with (a part of) the potential negative impact work derived from yours may have *in the users*. If you really want to help them, please do not allow the violation of their rights be carried through work derived from yours. I will try not to insist more on it, but I would be happy if just by insisting this bit I would get you to give an extra thought to the topic.

Now, regarding your use of Soil... Hmmm... Let's see... ;) In truth, I did not know whether this was on my hand or not. After some research, I have found an article by Richard Stallman for the Free Software Foundation on the topic of [selling exceptions to the GNU GPL](https://www.fsf.org/blogs/rms/selling-exceptions), which includes the following information (the emphasis is mine):

>  A copyleft license permits embedding in a larger program only if the whole combined program is released under that license; this is how it ensures extended versions will also be free. Thus, **users that want to make the combined program proprietary need special permission. Only the copyright holder can grant that**, and selling exceptions is one style of doing so.

From which I conclude your permission to use Soil does depend on me. Therefore, I hereby grant you access to use Soil (partially if you wish, and modifying it if you wish) in your MIT-licensed [Musicope](https://github.com/czb/musicope) project.

Finally, thanks for your explanation regarding the npm topic. I could not grasp all of it, but at least I have a general idea now.

**Comment by czb** [comment]
Just a quick comment :).

I believe that if the open source world was based only on GPL it would never have grown to the state where it is now. Simply because nobody would use these libraries in commercial projects. As I see it, GPL projects / libraries are only being used if there are no other more permissive alternatives of the same quality. GPL libraries moreover usually tend to be dual license paid libraries. Can you mention a couple of widely adopted GPL javascript libraries that are not dual license (paid)?

I moreover tend to believe statistics as majority usually tend to be right (with exceptions).

PS: https://softwareengineering.stackexchange.com/questions/81947/why-is-jquery-released-under-mit-and-not-lgpl

> When the goal is to have lots of people use your library, and not to try to force developers to conform to a certain ideology, that can be a useful thing.

> The latter are, IMO, much closer to the spirit of "free" software than the GPL family (after all, you can't force freedom on people).

> The LGPL offers more benefits to the software creator, whereas the MIT offers more benefits to the software user.

> If you want people to happily bundle your software with their software, choose the MIT license. If you want your software to be bundled separately and never as closely integrated with whatever package is using it, use the LGPL.

**Comment by inad9300** [comment]
As promised, I have released a new version which includes a few scripts to generate the type definitions semi-automatically :slightly_smiling_face: The source I have finally used is the TypeScript definition files, which I think makes the most sense since the project is relying on TypeScript already.

With this setup, I can now control which properties from the original type definitions make it to Soil's version of them. In particular, I made it so that index signatures (for certain interfaces) are not allowed when creating HTML elements. This way, `h.form([])` correctly raises an error.

Oddly enough, `h.select([])` does work. This is in my opinion due to a mistake in the HTML specification itself, which defines a `length` attribute for the `HTMLSelectElement` interface, which is writable! So effectively, you can assign, say, `5` to it, and 5 `HTMLOptionElement`s will pop up magically in your `<select>` element :confused:

Other properties that get filtered at the source are most read-only properties, and functions, so type-safety should have been greatly improved! Support for `aria-*` attributes has been added too.

One breaking change which might concern you was introduced. With the intention of simplifying the mental model, only an array can be passed as children of HTML elements. Previously, passing a single string was possible, as an exception, but you must now wrap it into an array on your side, e.g. `h.p({}, ['Hello, World!])`.
